references:
  commands:
    setup-docker: &setup-docker
      docker:
        - image: kurosame/circleci-node

version: 2
jobs:
  outdated:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Cache dependencies
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Outdated
          command: |
            PAYLOAD=`cat << EOF
            {
              "attachments": [
                {
                  "pretext": "portfolio's Outdated",
                  "text": '$(npm outdated)'
                }
              ]
            }
            EOF`
            curl -X POST -d "payload=$PAYLOAD" $SLACK_WEBHOOK_URL
  lighthouse:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Cache dependencies
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lighthouse
          command: ./node_modules/.bin/lighthouse --chrome-flags="--headless --no-sandbox" --output-path=./lighthouse-results.html $PORTFOLIO_APP_URL
      - store_artifacts:
          path: ./lighthouse-results.html
      - run:
          name: Send to Slack
          command: |
            PAYLOAD=`cat << EOF
            {
              "attachments": [
                {
                  "pretext": "portfolio's Lighthouse",
                  "text": "https://${CIRCLE_BUILD_NUM}-${CIRCLE_CI_REPOSITORY_ID}-gh.circle-artifacts.com/0/lighthouse-results.html",
                }
              ]
            }
            EOF`
            curl -X POST -d "payload=$PAYLOAD" $SLACK_WEBHOOK_URL

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: '00 0 * * 1'
          filters:
            branches:
              only:
                - master
    jobs:
      - outdated
      - lighthouse
