version: 2.1

orbs:
  node: circleci/node@6.0.0
  slack: circleci/slack@4.8.3

parameters:
  run-schedule:
    type: boolean
    default: false

jobs:
  lighthouse:
    executor:
      name: node/default
      tag: '16.13.0'
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lighthouse
          command: ./node_modules/.bin/lighthouse --chrome-flags="--headless --no-sandbox" --output-path=./lighthouse-results.html $PORTFOLIO_APP_URL
      - store_artifacts:
          path: ./lighthouse-results.html
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "portfolio's Lighthouse"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Open in browser"
                      },
                      "url": "https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/lighthouse-results.html"
                    }
                  ]
                }
              ]
            }

workflows:
  nightly:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - lighthouse
